service: s3-demo

provider:
  name: aws
  runtime: nodejs12.x

functions:
  updloadFile:
    handler: handler.updloadFile
    events:
      - http:
          path: /upload
          method: get

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-dotenv-plugin
