service: invoke-another-lambda-demo

provider:
  name: aws
  runtime: nodejs12.x

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /hello
          method: get

  test:
    handler: handler.test

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-dotenv-plugin
